### PR TITLE
Add login actions needed for unit tests

### PR DESCRIPTION
**Pull request by llewelld**
Adds "add" and "removeAll" actions to the "embedui:logins" notifications observed by LoginsHelper.

These actions are used by the unit tests.

### CODE REVIEW

**Comment by llewelld** [comment]
This is a pre-requisite for https://github.com/sailfishos/sailfish-browser/pull/839.

**Comment by llewelld** [comment]
@atatarov, @okodron, github won't let me add you directly as reviewers unfortunately, but I'd appreciate your input on this nevertheless.

**Review by okodron — APPROVED** [review]

**Review by rainemak — APPROVED** [review]
LGTM

**Review by atatarov — APPROVED** [review]

**Comment by llewelld** [comment]
Rebased.

**Pull request merged**
