### PR TITLE
Fix javascript console logging output. JB#55880 OMP#JOLLA-435

### PR DESCRIPTION
**Pull request by llewelld**
This updates the logging triggered by "console-api-log-event" so that the passed objects are unbundled and displayed correctly.

Most of the new code has been taken from GeckoViewConsole.jsm, here:

https://github.com/sailfishos-mirror/gecko-dev/blob/2834d64c4b16c7b93857fd58ca55dc76d8176bfd/mobile/android/modules/geckoview/GeckoViewConsole.jsm#L55

As before `EMBED_CONSOLE="stacktrace"` must be set in the environment in order to activate this logging.

### CODE REVIEW

**Comment by llewelld** [comment]
Sorry, my review request was premature. Switching to a draft.

**Comment by llewelld** [comment]
The issues I hit should now be fixed, so this should now be properly ready for review.

**Comment by llewelld** [comment]
The output console output with the test page now looks something like this:
```
$ EMBED_CONSOLE="stacktrace" sailfish-browser https://www.flypig.co.uk/tests/stacktrace.html
...
Frame script: embedhelper.js loaded
Content JS: https://www.flypig.co.uk/tests/stacktrace.html, function: init, message: This is a debug log
Content JS: https://www.flypig.co.uk/tests/stacktrace.html, function: init, message: [JavaScript Warning: "This is a warning log"]
Content JS: stacktrace.html, function: init, line: 10, message: This is a trace log
Content JS: stacktrace.html, function: frame, line: 20, message: This is a trace log with 4 frames
Content JS: https://www.flypig.co.uk/tests/stacktrace.html, function: init, message: [JavaScript Error: "This is an error log"]
JavaScript error: https://www.flypig.co.uk/tests/stacktrace.html, line 14: Error: This is throwing an error
CONSOLE message:
[JavaScript Error: "Error: This is throwing an error" {file: "https://www.flypig.co.uk/tests/stacktrace.html" line: 14}]
init@https://www.flypig.co.uk/tests/stacktrace.html:14:15
onload@https://www.flypig.co.uk/tests/stacktrace.html:1:1
```

**Review by rainemak — APPROVED** [review]
LGTM! Btw, it's good a habit to use "Fixes JB#55880" when a change fixes a task/bug.

**Review by okodron — APPROVED** [review]

**Pull request merged**
