### PR TITLE
rememberValidityOverride additional param

### PR DESCRIPTION
**Pull request by b100dian**
Allows working around invalid certificate by temporary adding it - the method has one more param

### CODE REVIEW

**Comment by llewelld** [comment]
Great; thanks for this @b100dian.

Some notes collected while testing this. The problem can be triggered by viewing the [badssl expired cert](https://expired.badssl.com/) page. Without @b100dian's change, selecting the button to ignore the cert error and visit the site anyway fails with the following error:
```
JavaScript error:
    file:///usr/lib64/mozembedlite/components/EmbedLiteErrorPageHandler.js,
    line 162: NS_ERROR_XPC_NOT_ENOUGH_ARGS: Not enough arguments 
    [nsICertOverrideService.rememberValidityOverride]
```

This is due to a missing `aOriginAttributes` parameter that @b100dian has now added. The change can be found in [D91962](https://phabricator.services.mozilla.com/D91962) and the new signature (taken from `nsICertOverrideService.idl` looks like this:

```c
  /**
   *  The given cert should always be accepted for the given hostname:port,
   *  regardless of errors verifying the cert.
   *  Host:Port is a primary key, only one entry per host:port can exist.
   *  The implementation will store a fingerprint of the cert.
   *  The implementation will decide which fingerprint alg is used.
   *
   *  Each override is specific to exactly the errors overridden, so
   *  overriding everything won't match certs at the given host:port
   *  which only exhibit some subset of errors.
   *
   *  @param aHostName The host (punycode) this mapping belongs to
   *  @param aPort The port this mapping belongs to, if it is -1 then it
   *          is internaly treated as 443
   *  @param aCert The cert that should always be accepted
   *  @param aOverrideBits The precise set of errors we want to be overriden
   */
  [binaryname(RememberValidityOverride), noscript, must_use]
  void rememberValidityOverrideNative(in AUTF8String aHostName,
                                in int32_t aPort,
                                in const_OriginAttributesRef aOriginAttributes,
                                in nsIX509Cert aCert,
                                in uint32_t aOverrideBits,
                                in boolean aTemporary);
  [binaryname(RememberValidityOverrideScriptable), implicit_jscontext, must_use]
  void rememberValidityOverride(in AUTF8String aHostName,
                                in int32_t aPort,
                                in jsval aOriginAttributes,
                                in nsIX509Cert aCert,
                                in uint32_t aOverrideBits,
                                in boolean aTemporary);
```

**Comment by llewelld** [comment]
I tested this and it worked nicely; great work @b100dian. Just one thought: would it make sense to pass in `target.nodePrincipal.originAttributes` as the new parameter? Although I won't claim to fully understand the importance of the parameter, this would seem to more closely match how it's used in the [upstream change](https://phabricator.services.mozilla.com/D91962) outside of the test code.

**Review by llewelld — COMMENTED** [review]
I tested this and it worked nicely; great work @b100dian. Just one thought: would it make sense to pass in `target.nodePrincipal.originAttributes` as the new parameter? Although I won't claim to fully understand the importance of the parameter, this would seem to more closely match how it's used in the [upstream change](https://phabricator.services.mozilla.com/D91962) outside of the test code.

**Comment by b100dian** [comment]
> would it make sense to pass in `target.nodePrincipal.originAttributes` as the new parameter? 

Thanks for pointing out the original change. My grepping probably showed up test code that just used `{}`. As soon as I am able to test your proposal, I'll make the change - and if you already tested please make a separate PR and close this one.

**Comment by llewelld** [comment]
Thanks @b100dian. I did some cursory testing but didn't get a chance to do anything properly. I think it makes most sense, if you don't mind, making the change here.

**Comment by b100dian** [comment]
> Thanks @b100dian. I did some cursory testing but didn't get a chance to do anything properly. I think it makes most sense, if you don't mind, making the change here.

Unfortunately I did not have time to test the change due to other environment errors.
If you have yourself tested `target.nodePrincipal.originAttribute` I can amend the commit. Thanks!

**Comment by llewelld** [comment]
> If you have yourself tested `target.nodePrincipal.originAttribute` I can amend the commit. Thanks!

I tested using a straight replacement; something like this:
```javascript
            let attrs = target.nodePrincipal.originAttributes;
            overrideService.rememberValidityOverride(uri.asciiHost, uri.port, attrs,
                                                     cert, flags, temporary);
```
This allowed overriding the bad certificate and I didn't notice any regressions.

**Comment by b100dian** [comment]
Done, thanks again!

**Review by llewelld — APPROVED** [review]
Thanks for this. I gave it another run through and it all worked nicely.

**Pull request merged**
